[package]
name = "home-control"
author = "Julien Kauffmann <julien.kauffmann@freelan.org>"
description = "A home automation interface for embedded systems."
license = "MIT"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
