[package]
name = "home-control"
authors = ["Julien Kauffmann <julien.kauffmann@freelan.org>"]
description = "A home automation interface for embedded systems."
license = "MIT"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-web-static-files = "3.0.5"
anyhow = "1.0.51"
clap = "2.34.0"
log = "0.4.14"
simplelog = "0.11"

[build-dependencies]
actix-web-static-files = "3.0"